---

- name: Include 'inventory' tasks.
  include: ec2/inventory.yml
  static: false
  when: groups['ec2'] is defined

- name: Check environment for AWS_EC2_STATE.
  set_fact:
    ec2_state: "{{ lookup('env','AWS_EC2_STATE') | default(ec2_state, True) }}"

- name: Compile a list of unique regions where EC2 VMs will be provisioned
  set_fact:
    ec2_regions: "{{ (ec2_regions + [ item.value.region | default(ec2_region) ])|unique }}"
  with_dict: "{{ cloud }}"

- name: Include tasks to create missing EC2 keypairs.
  include: ec2/keypairs.yml

- name: Include tasks to create missing EC2 security groups.
  include: ec2/sec_groups.yml

- name: Include tasks to ensure the proper state and group of EC2 VMs.
  include: ec2/ensure.yml

- name: Include tasks to remove unused EC2 security groups.
  include: ec2/sec_groups_cleanup.yml

- name: Include tasks to set hostnames of EC2 VMs.
  include: ec2/hostnames.yml
  static: false
  when: aws_set_hostnames and (aws_zone is defined)

- name: Include tasks to add hostname DNS entries for EC2 VMs.
  include: ec2/domains.yml
  static: false
  when: aws_manage_hostname_dns_records and (aws_zone is defined)

