---

- include: '../../common/ssh_pub_key.yml'

- name: Compile a list of unique regions where EC2 VMs will be provisioned
  set_fact:
    ec2_regions: "{{ (ec2_regions + [ item.value.region | default(ec2_region) ])|unique }}"
  with_dict: "{{ cloud }}"

- name: Create an EC2 keypair
  ec2_key:
    name: "{{ lookup('env','USER') }}" # the current user
    key_material: "{{ ssh_pub_key }}"
    region: "{{ item }}"
    wait: yes
  with_items: "{{ ec2_regions }}"

- name: Create missing EC2 VMs
  ec2:
    instance_tags:
      Name: "{{ item.key }}"
    instance_type: "{{ item.value.instance_type | default(ec2_instance_type) }}"
    region: "{{ item.value.region | default(ec2_region) }}"
    image: "{{ item.value.image | default(ec2_image) }}"
    key_name: "{{ item.value.key_name | default(lookup('env','USER')) }}"
    wait: yes
    state: "{{ item.value.state | default(ec2_state) }}"
  when: (item.value.state|default(ec2_state) != 'absent') and (cached_ec2_vms[item.key] is not defined)
  with_dict: "{{ cloud.aws.ec2 }}"
  register: new_ec2_vms

- name: Add newly created EC2 VMs to cached inventory
  set_fact:
    cached_ec2_vms: "{{ cached_ec2_vms | combine( { item.item.key : item.instances.0.id } ) }}"
  when: cached_ec2_vms[item.item.key] is not defined and item.changed
  with_items: "{{ new_ec2_vms.results }}"

- name: Add newly created EC2 VMs to groups/inventory
  add_host:
    hostname: "{{ item.item.key }}"
    groups: "all,cloud,ec2,{{ item.item.value.group|default('all') }}"
    ansible_host: "{{ item.instances.0.public_ip }}"
    ansible_ssh_host: "{{ item.instances.0.public_ip }}"
    public_ip: "{{ item.instances.0.public_ip }}"
    ec2_tag_Name: "{{ item.item.key }}"
    status: "{{ item.instances.0.state }}"
  when: item.changed
  with_items: "{{ new_ec2_vms.results }}"
