---
language: php

dist: trusty

sudo: false

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    - python-yaml
    - python-jinja2
    #- python-paramiko
    #- python-pip
    #- python-pycurl

env:
  - BEHAT_TAGS="~@slow"
  - BEHAT_TAGS="@slow"


before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user `whoami` chube
  - make behat

script:
  - . d
  - behat --tags="~@disabled&&~@wip&&$BEHAT_TAGS"
