language: php
dist: trusty
sudo: false
os:
- linux
addons:
  apt:
    packages:
    - python-yaml
env:
  matrix:
  - TEST_TARGET="linode-test"
  - TEST_TARGET="aws-ec2-test"
  - TEST_TARGET="linode-test-slow"
  - TEST_TARGET="aws-ec2-test-slow"
  global:
  - secure: mWik2wEVcU5LumsjhmXPAN5bN5OQsgqx0kNZiLorMlF8a7NaL95jc4CKpQF1swRYr8PhU+p8zWCKwEg/bTqn8Qp/+AYKkeQzulCc6j7xDFGZvCsgXDvfm4ItuMEw47N2JmOJfKWlBP2FznDkCYB+evS279SmHu3cwOEqFn3PExuU3OSvG34VGm78psF/Xpu2u079MXYsXD1mvxpw1aFOUjlkKb+hrT7N/2z8W4ea2N49BRcdDbV7YuPBf0EYuQAhT+iQIg4Se/FRGqv2DqrwN135Z2Q/BwgU9Sp2UE4OsyDVjCNeTI66SuZtMnN3tBmyJfnpnNSRZCf+nRq7oZRP4Zr0+W1J0PR4Mg2VVOnzjw/r89ur6UawBbX+WLhymlwGgpK6SEOyzPw5Ve5Ac09OqLJz7URZHcq4njUqjm8KXaTedAAUD9MDHZYcjyffpOA26Fa0Vq5idg/x3pBehzNCb9/un+ACNlLOf6vJBaNZgtPKDZQR7hyJDYNus318Cu9q8Qz4D4+J9EXl1GApa7HKZG8V4oSTP4rl5iYoLzDAPkomMvAK1/Dcc6NcHNRpKUy8kxJYa38pB17U5pxqk2oVvY50SX9HkX+VEWW0t4H1XBYzfzrsBLQDCPAqB1CB4WolSq7Qf8yN8EOblW6oNc9bcYvcgpq1lk/DJIXLhjAnxaA=
  - secure: lUuoG6ViukwHAPSHuMs3qeZ8Ic7twE+qUmUTaooJ9Ss3L162aGBmrjzFM32HQsmJCKvQ0lVeH+J36JKbZ7LZMthAJ2uYFZ+Zb+2oL73G5/s+QDDhKD90NfPQ1AbOYzrCR8i7r8V5MFivkTz5uZhimQoI0rDS8VB0VdVdDu5X3LNH2A4p/Sq4SaqKcZcE6RkmFpxB6QftUlAKW8Fp4nK6rNu+olk1ukW8v/c8kfogZxM1p7+MXPAJ8X8r0ZUaobtVdUrKWd9Q3/oiRfUw8OR1hik3tdt5aJYMZCcMWwFGbb1nCpRrFHtT0rXvfqBckpZnQqluHFDvD/7mkCjYq/XHAL5Pwj12nRk1vOBdCkHk1cDQqKqS8/2+Xq+OpmU1VK3sfNjFDPozD+8m6/2tFJxvjgJMDSuTc2AQ7pMzDs7jVLCPGFlB13l0A/xMhXIcYpKXNm319ko9U3GCXlZd3e9w7rZluUds1OP5VF7+O4ycGH/fRDSdrIml7d8AZD6kl7qy93nftmQSgXrknFzNZMEuc9iyAsdfioj8qiFvYWsWcSPLze7zAnIkix3Z8qxmaXxsg0fdvngniFDFD+woamKBzfN7st3My38UDMuwALqq+wUEBiV1001ABrT2TmQPHcM2hP0BMkXCQzZrz+aPe+91TMReleDX5WUCp+W8CkVTv4o=
  - secure: IGwxpjgsccaTPLXd0yarVZMga9h8fZsiIDV535hu5HtHj19bOo19eWFXgSyjHG6zvgbdBNg0H3Q58P1+xJ31ggWYost4urOKD091dnbdu6i7J+uzuw4KdLe/LVFQnlW9OFZUPJLm9vc1JupNf7NouJoO8eiuHyQg7XyYMUN4iYWTMGsipCiVM4Nu796BuNXwlPfeqYmzvIuf4B/ByOvEj7DtTXv9/+jXbbu56znbGAlhMHPPGQFuADqoyyeif2vH8YBkBEOFtONkRhWcI/3H14GnSVi/owhoP5eXs9WX7jvoLPmYSR1p8gh4HG6sNluV4nSVh22bvElyfkgM+Rb/zu5piWGTUURNAXQNvM1i2aE2rTWFB6YUy06D/ey9uF4R4H0pYbbdtKxAPOLGSMOiGs8HHoqfqbTXRAM3gsfWLEplpYoIYxh8OhjrLb3UFA/wZ7y49GSk9Pw5m9XHA0qI79gei90SF25xEAkP6HYaK1SJxq2AegOGhqPh/Q6RAMa5eGGlH7bPOYClOwG8ZNvaUHzAQVBDrh7VetCJA8YU7P61P+pQNhZryXnXJdMTuZ8J7uc21k2aLJJoIWgWNGNGzfXdOvf6g6mRXgndBHel5jqbu4cLgS0xy4FOPXpIu9p7Ti1ln1UhTZ6YRfeOPBH4dRHbmrgTZOpItqqDC8TWpRg=
before_script:
- export PATH=$HOME/.local/bin:$PATH
- pip install --upgrade pip
- pip install --user chube boto jinja2
- make behat
script:
- ". d"
- make $TEST_TARGET
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
