---

- name: Find public key to use for later server configuration.
  set_fact:
    ssh_pub_key: "{{ lookup('file', item) }}"
  with_first_found:
  - files:
    - '~/.ssh/id_rsa.pub'
    skip: true

- name: Create missing linodes
  # ref.: http://docs.ansible.com/ansible/linode_module.html
  linode:
    name: "{{ item.key }}"
    plan: "{{ item.value.plan | default('1') }}"
    datacenter: "{{ item.value.datacenter | default('2')  }}"
    distribution: "{{ item.value.distro | default('124') }}"
    ssh_pub_key: "{{ ssh_pub_key | default(omit) }}"
    wait: yes
    state: "{{ item.value.state | default(linode_state) }}"
  when: cached_linodes[item.key] is not defined
  with_dict: "{{ cloud.linode }}"
  register: new_linodes

- name: Add newly created linodes to cached inventory
  set_fact:
    # Strip the ID from the label, to get the name, then map to the ID.
    cached_linodes: "{{ cached_linodes | combine( { item.item.key : item.instance.id } ) }}"
  when: cached_linodes[item.item.key] is not defined and item.instance.id is defined
  with_items: "{{ new_linodes.results }}"

