---

- name: Map linodes inventory by name (for idempotence)
  set_fact:
    # Strip the ID from the label, to get the name, then map to the ID.
    cached_linodes: "{{ cached_linodes | combine( {hostvars[item].label|regex_replace('^[^_]*_',''): hostvars[item].api_id} ) }}"
  with_items: "{{ hostvars['localhost']['groups'][''] }}"

