---

- name: Include 'inventory' tasks.
  include: linode/inventory.yml
  static: false
  when: groups['linode'] is defined

- name: Check environment for LINODE_STATE.
  set_fact:
    linode_state: "{{ lookup('env','LINODE_STATE') | default(linode_state, True) }}"

- name: Include tasks to create missing Linode VMs.
  include: linode/create.yml

- name: Include tasks to ensure the proper state and group of Linode VMs.
  include: linode/ensure.yml
  static: false
  when: cached_linode_vms != {}


- name: Include tasks to set hostnames of Linode VMs.
  include: linode/hostnames.yml
  static: false
  when: linode_set_hostnames and (cloud.linode is defined) and (linode_zone is defined)

- name: Include tasks to add hostname DNS entries for Linode VMs.
  include: linode/domains.yml
  static: false
  when: linode_manage_hostname_dns_records and (linode_zone is defined)

