---
#- name: Checking environment for LINODE_STATE
- set_fact:
    linode_state: "{{ lookup('env','LINODE_STATE') | default('present', true) }}"

- name: Ensure the state of existing linodes
  # ref.: http://docs.ansible.com/ansible/linode_module.html
  linode:
    name: "{{ item.key }}"
    linode_id: "{{ cached_linodes[item.key] | default(omit) }}"
    wait: yes
    state: "{{ item.value.state | default(linode_state) }}"
  when: cached_linodes[item.key] is defined
  with_dict: "{{ cloud.linode }}"

- name: Create missing linodes
  # ref.: http://docs.ansible.com/ansible/linode_module.html
  linode:
    name: "{{ item.key }}"
    plan: "{{ item.value.plan | default('1') }}"
    datacenter: "{{ item.value.datacenter | default('2')  }}"
    distribution: "{{ item.value.distro | default('124') }}"
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    wait: yes
    state: "{{ item.value.state | default(linode_state) }}"
  when: cached_linodes[item.key] is not defined
  with_dict: "{{ cloud.linode }}"
