---

- name: Include 'get_distros' tasks
  include: get_distros.yml
  when: op == 'get_distros'

- name: Include 'inventory' tasks
  include: inventory.yml
  when: hostvars['localhost']['groups']['linode'] is defined

- name: Check environment for LINODE_STATE
  set_fact:
    linode_state: "{{ lookup('env','LINODE_STATE') | default(linode_state, true) }}"

- name: Include tasks to create missing linodes
  include: create.yml
  when: op == 'linodes' and cloud.linode is defined

- name: Include tasks to ensure the proper state and group of linodes
  include: ensure.yml
  when: op == 'linodes' and cached_linodes != {}

