---

- include: '../common/ssh_pub_key.yml'

- name: Create missing Linode VMs
  # ref.: http://docs.ansible.com/ansible/linode_module.html
  linode:
    name: "{{ item.key }}"
    plan: "{{ item.value.plan | default('1') }}"
    datacenter: "{{ item.value.datacenter | default('2')  }}"
    distribution: "{{ item.value.distro | default('124') }}"
    ssh_pub_key: "{{ ssh_pub_key | default(omit) }}"
    wait: yes
    state: "{{ item.value.state | default(linode_state) }}"
  when: (item.value.state|default(linode_state) != 'absent') and (cached_linode_vms[item.key] is not defined)
  with_dict: "{{ cloud.linode }}"
  register: new_linode_vms

- name: Add newly created Linode VMs to cached inventory
  set_fact:
    cached_linode_vms: "{{ cached_linode_vms | combine( { item.item.key : item.instance.id } ) }}"
  when: cached_linode_vms[item.item.key] is not defined and item.changed
  with_items: "{{ new_linode_vms.results }}"

- name: Add newly created Linode VMs to groups/inventory
  add_host:
    hostname: "{{ item.instance.name }}"
    groups: "all,cloud,linode,{{ item.item.value.group|default('all') }}"
    ansible_host: "{{ item.instance.ipv4 }}"
    ansible_ssh_host: "{{ item.instance.ipv4 }}"
    public_ip: "{{ item.instance.ipv4 }}"
    linode_name: "{{ item.item.key }}"
    status: "{{ item.instance.status | regex_replace('^Running$', '1') }}"
  when: item.changed
  with_items: "{{ new_linode_vms.results }}"
