---
- hosts: localhost
  connection: local

  tasks:

  - name: Look up Linode API key from environment.
    set_fact:
      linode_api_key: "{{ lookup('env', 'LINODE_API_KEY') }}"
    when: linode_api_key is not defined

  - name: Add header for distro list.
    set_fact:
      distros: "ID - Label\n----------\n"

  - name: Make call to Linode API.
    uri:
      url: "https://api.linode.com/?api_key={{ linode_api_key }}&api_action=avail.distributions"
      return_content: yes
    register: distros_from_api

  - name: Build list of distributions.
    set_fact:
      distros: "{{ distros }}{{ item.DISTRIBUTIONID }}: {{ item.LABEL }}\n"
    with_items: "{{ distros_from_api.json.DATA }}"
    when: distros_from_api.json is defined

  - name: Print list of distributions.
    command: echo "{{ distros }}"
    register: distro_output
    changed_when: false

  - debug:
      msg: "{{ distro_output.stdout_lines }}"

